/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcButton {
    'buttonTitle': string;
  }
  interface WcButtonAttributes extends StencilHTMLAttributes {
    'buttonTitle'?: string;
  }

  interface WcCard {}
  interface WcCardAttributes extends StencilHTMLAttributes {}

  interface WcImage {
    'imageAlt': string;
    'imageSrc': string;
  }
  interface WcImageAttributes extends StencilHTMLAttributes {
    'imageAlt'?: string;
    'imageSrc'?: string;
  }

  interface WcLink {
    'linkHref': string;
    'linkTitle': string;
  }
  interface WcLinkAttributes extends StencilHTMLAttributes {
    'linkHref'?: string;
    'linkTitle'?: string;
  }

  interface WcPrice {
    'priceNumber': string;
  }
  interface WcPriceAttributes extends StencilHTMLAttributes {
    'priceNumber'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcButton': Components.WcButton;
    'WcCard': Components.WcCard;
    'WcImage': Components.WcImage;
    'WcLink': Components.WcLink;
    'WcPrice': Components.WcPrice;
  }

  interface StencilIntrinsicElements {
    'wc-button': Components.WcButtonAttributes;
    'wc-card': Components.WcCardAttributes;
    'wc-image': Components.WcImageAttributes;
    'wc-link': Components.WcLinkAttributes;
    'wc-price': Components.WcPriceAttributes;
  }


  interface HTMLWcButtonElement extends Components.WcButton, HTMLStencilElement {}
  var HTMLWcButtonElement: {
    prototype: HTMLWcButtonElement;
    new (): HTMLWcButtonElement;
  };

  interface HTMLWcCardElement extends Components.WcCard, HTMLStencilElement {}
  var HTMLWcCardElement: {
    prototype: HTMLWcCardElement;
    new (): HTMLWcCardElement;
  };

  interface HTMLWcImageElement extends Components.WcImage, HTMLStencilElement {}
  var HTMLWcImageElement: {
    prototype: HTMLWcImageElement;
    new (): HTMLWcImageElement;
  };

  interface HTMLWcLinkElement extends Components.WcLink, HTMLStencilElement {}
  var HTMLWcLinkElement: {
    prototype: HTMLWcLinkElement;
    new (): HTMLWcLinkElement;
  };

  interface HTMLWcPriceElement extends Components.WcPrice, HTMLStencilElement {}
  var HTMLWcPriceElement: {
    prototype: HTMLWcPriceElement;
    new (): HTMLWcPriceElement;
  };

  interface HTMLElementTagNameMap {
    'wc-button': HTMLWcButtonElement
    'wc-card': HTMLWcCardElement
    'wc-image': HTMLWcImageElement
    'wc-link': HTMLWcLinkElement
    'wc-price': HTMLWcPriceElement
  }

  interface ElementTagNameMap {
    'wc-button': HTMLWcButtonElement;
    'wc-card': HTMLWcCardElement;
    'wc-image': HTMLWcImageElement;
    'wc-link': HTMLWcLinkElement;
    'wc-price': HTMLWcPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
